services:
  - type: web
    name: shopee-video-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: ALLOWED_ORIGIN
        value: "*"   # đổi thành domain 123host thật sau khi có, cách nhau bởi dấu phẩy nếu nhiều domain
